# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_kv"
version = "0.15.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of the Deno database API"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
deno_core.workspace = true
hex.workspace = true
num-bigint.workspace = true
rusqlite.workspace = true
serde.workspace = true
